sonar.projectKey=Circular-keyword-matcher
sonar.projectName=Circular keyword matcher
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.test.js,**/dist/**,**/build/**,**/.git/**

sonar.sourceEncoding=UTF-8